### ISSUE TITLE
Recording does not wait for pending requests to complete at the end of a test case, making them non-deterministic

### ISSUE THREAD

**Issue by antischematic** [Sam152/cypress-replay#12]
Given a test that records some data when a page is visited:

```ts
describe(() => {
  enableCypressReplay(ReplayMode.Recording);

  it("should visit", () => {
    cy.visit("/")
  })

  it("should click a button", () => {
    cy.get("button").click()
  })

  it("should check something is visible", () => {
    cy.get("something").should("be.visible")
  })
})
```

Several fetch requests are initiated when the page is visited. The `visit` command completes before all of the requests are resolved.

Expected: The recorded data should be stored in the `should visit` fixture, which initiated the request.

Actual result: The recorded data are spread across the `should visit`, `should click a button` or `should check something is visible` fixture, depending on how fast or slow each network request is resolved.

There is a race condition caused by the recorder here:
Source: https://github.com/Sam152/cypress-replay/blob/1.0/src/record/recordRequests.ts#L38

Each time a test completes it saves the result of any resolved requests, but does not keep track of pending requests. These pending requests are then carried over to the next test. When trying to replay these tests later, the stub will be missing because it was stored in the wrong file, which in some cases causes my tests to fail due to flakes.

I am currently working around this problem by using `cypress-network-idle` to force each test to wait for in-flight requests to finish before progressing to the next test. Ideally the data recorder should track the original context each request is made from so it can store the result in the correct file, and/or force tests to wait for network activity to be idle before proceeding to the next test.

**Comment by Sam152** [comment]
I have noticed this as well and have resolved it by either: making sure there is at least one assertion that depends on the final request that is made from a specific test or sleeping for some duration. I think the `cypress-network-idle` plugin sounds like a pretty good solution as well.

Perhaps some of these solutions should be documented under "best practices" in the README? The plugin could also be made a dependency, but that might be increasing the weight and complexity for users who don't run into this problem.
